### ISSUE TITLE
Sidebar covering content

### ISSUE THREAD

**Issue by HsuTimothy** [trendmicro-frontend/react-sidenav#11]
Hi! I was wondering is there a way to get the sidebar to not appear on top of other objects?

For example, in this picture, the sidebar is slightly covering the map a bit (top left corner especially)

![image](https://user-images.githubusercontent.com/14950271/47825630-3a3c5000-dd30-11e8-8824-9257e95a09d6.png)

Thanks for your help!

**Comment by Hienphamthe** [comment]
I think you could add left-padding to your main page (the map) so that the width is equal to the width of the sidebar
