### ISSUE TITLE
expanded sidebar

### ISSUE THREAD

**Issue by Hienphamthe** [trendmicro-frontend/react-sidenav#12]
Hi,
Could anyone show me a way to blur the mainpage content when the sidebar is expanded. Like in this youtube picture. 

![image](https://user-images.githubusercontent.com/25283070/49509905-00a6b980-f887-11e8-83d9-6b0c43f35079.png) 

Thanks all.

**Comment by cheton** [comment]
See the demo at https://trendmicro-frontend.github.io/react-sidenav/ by clicking on the <kbd>Styled Component</kbd> button.

You can set the expanded state so you can make your main page blur when the sidebar is expanded.

https://github.com/trendmicro-frontend/react-sidenav/blob/master/examples/Styled/index.jsx#L60
```js
class MyComponent extends React.Component {
    state = {
        expanded: false
    };

    render() {
        const { expanded } = this.state;

        return (
            <Fragment>
                <SideNav
                    style={{ minWidth: expanded ? navWidthExpanded : navWidthCollapsed }}
                    onToggle={expanded => {
                        this.setState({ expanded: expanded });
                    }}
                >
                    {/* sidenav components here */}
                </SideNav>
                <Main expanded={expanded}>
                    {/* main content here */}
                </Main>
            </Fragment>
        );
    }
```
