### ISSUE TITLE
Sub menu with sub menu

### ISSUE THREAD

**Issue by vademyanchik** [trendmicro-frontend/react-sidenav#13]
![image](https://user-images.githubusercontent.com/11206790/49644660-215b4480-fa2a-11e8-8cc3-eeb7bb0984f5.png)
Is there any way to do menu like on the picture above? Thanks for help!

**Comment by masoomeg** [comment]
@vademyanchik  did you find the solution?

**Comment by alex-dgx** [comment]
Hi, any solutions or any idea where i can find a solution?

**Comment by roth1002** [comment]
How about wrap a render props component ?
