### ISSUE TITLE
Styled nav sliding animation is not smooth

### ISSUE THREAD

**Issue by Hienphamthe** [trendmicro-frontend/react-sidenav#16]
Hi,
Does any one observe the same issue as me? On the demo, with normal sidenav, animation while expanding and collapsing go smoothly. Whereas, regarding styled sidenav, it does not. Especially when collapsing, sidebar shrinks faster than the gray cover of the mainpage. This lead to a small white delay between them. 
Please correct me if I am wrong. Or show me how to solve it. Thanks

**Comment by aakhan89** [comment]
yes, same here,

@cheton kindly guide us
