### ISSUE TITLE
Couldn't change Sidebar background with custom className property.

### ISSUE THREAD

**Issue by t-harison** [trendmicro-frontend/react-sidenav#17]
The order of objects during the classNames merge is wrong, that not allow custom CSS to customize the SideBar component.

Look at this line : https://github.com/trendmicro-frontend/react-sidenav/blob/master/src/SideNav.jsx#L130. The className property must be at least, I think. Thanks.

```
className={cx(
	styles.sidenav, 
	{
		[styles.disabled]: disabled,
        [styles.expanded]: expanded,
        [styles.collapsed]: !expanded
    },
	className
)}
```

**Comment by Daniellunsc** [comment]
I changed the backgroud using the style props. 

`<SideNav
                onSelect={(selected) => {
                    // Add your code here
                }}
                style={{backgroundColor: '#2185D0'}}
            >`

And yes, i think it needs a more detailed documentation about how to customize it.

**Comment by aakhan89** [comment]
simply wrap like below

`const StyledSideNav = styled(SideNav)`
    position: fixed;
    background: #00547B;
    z-index: 1031;
`;`
