### ISSUE TITLE
use @trendmicro/react-sidenav into a personal npm lib

### ISSUE THREAD

**Issue by hermes561** [trendmicro-frontend/react-sidenav#18]
Hello guys.
I'm a beginner in Rect and maybe I've done something wrong. 
I wanted to create my own lib in npm and one of elements was a sidenav using  @trendmicro/react-sidenav: 

```jsx
import React, { Component } from 'react';
import SideNav, { NavItem, NavIcon, NavText } from '@trendmicro/react-sidenav';
import './index.css';
import ClickOutside from './ClickOutside';
import '@trendmicro/react-sidenav/dist/react-sidenav.css';
import PropTypes from 'prop-types';

const propTypes = {
    sidebarOpen: PropTypes.bool,
    sidebarSelected: PropTypes.string,
    sidebarItems: PropTypes.array
}

const defaultProps = {
    sidebarOpen: false,
    sidebarSelected: 'home',
    sidebarItems: [
        {id:'home', icon:"fa fa-fw fa-home", type:'link',link:'/', text:'Home'}
    ]
}

class HermeSidebar extends Component {
  constructor(props) {
    super(props);
    this.sidenav = React.createRef();
  }  
  state = {
      expanded: true
  }
  
  componentDidMount() {
      this.setState({
          expanded: this.props.sidebarOpen
      });
  }
  render() {
    const {sidebarItems, sidebarSelected} = this.props;  
    const sidebarOpen = this.state.expanded;
    
    const navItems = sidebarItems ? sidebarItems.map(itemBar => {
        return (
            <NavItem eventKey={itemBar.id} key={itemBar.id} expanded={sidebarSelected.indexOf(itemBar.id+'/') !==-1} >
                { itemBar.icon ? (
                    <NavIcon>
                        <i className={itemBar.icon} style={{ fontSize: '1.75em' }} />
                    </NavIcon>
                  ) : (null)
                } 
                {  itemBar.text ? (
                    <NavText>
                        { itemBar.type === 'link' ? (
                                <a href={itemBar.link} ><b>{itemBar.text}</b></a>
                            ) : (<b>{itemBar.text}</b>)
                        }
                    </NavText> 
                  ) : (null)
                }   
                { itemBar.items ? (
                        itemBar.items.length ? (
                            itemBar.items.map((itemSub) => {
                                return (
                                    <NavItem eventKey={itemBar.id+'/'+itemSub.id} key={itemSub.id}>
                                        <NavText>
                                        {   itemSub.type === 'link' ? (
                                                <a href={itemSub.link} target={itemSub.target ? itemSub.target:''}><b>{itemSub.text}</b>
                                                   <br /><small> { itemSub.summary ? ('( '+itemSub.summary+' )') : (null)}</small>
                                                </a>
                                            ) : (<b>{itemSub.text}</b>)
                                        }
                                        
                                       
                                        </NavText>        
                                    </NavItem>
                                )    
                            })
                            
                       ) : (null) 
                    ) : (null)
                }    
            </NavItem>
        )   
    }): (
        <NavItem eventKey="no_data"></NavItem>
    )
   
    return (
      <div className="Ceva">
        <ClickOutside
            onClickOutside={() => {
                this.setState({ expanded: false });
            }}
        >
            <SideNav
                className ="globalSidebar"
                expanded={sidebarOpen}
                onToggle={(expanded) => {
                    this.setState({ expanded });
                }}
                ref={this.sidenav}
            >
                <SideNav.Toggle  ref={this.sidenav.toggle} />
                <SideNav.Nav defaultSelected={sidebarSelected} ref={this.sidenav.nav} >
                    {navItems}
                </SideNav.Nav>
            </SideNav>
        </ClickOutside>
      </div>
    );
  }
}

HermeSidebar.propTypes = propTypes;
HermeSidebar.defaultProps = defaultProps;

export  {
    HermeSidebar,
    ClickOutside
};

```

This works into a normal react app:
import {HermeSidebar} from './HermeSidebar'

but I wanted to use the component as a npm Component:
npm install react-sidebar-herme-nnew
import {HermeSidebar} from 'react-sidebar-herme-nnew/lib/HermeSidebar';

<HermeSidebar sidebarOpen={sidebarOpen} sidebarSelected={sidebarSelected} sidebarItems={sidebarItems} />

Here is the problem. I'm stack with this error and I didn't figured out how to fix it:

"Element ref was specified as a string (inner) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.
./src/index.js
src/index.js:8
 ReactDOM.render(<App />, document.getElementById('root'));"
  
here it's my pack:
package.json:
{
    "name": "react-sidebar-herme-nnew",
    "version": "1.0.1",
    "description": "navbar",
    "main": "/lib/HermeSidebar.js",
    "license": "MIT",
    "scripts": {
        "build": "webpack"
    },
    "peerDependencies": {
        "prop-types": "^15.6.0",
        "react": "^16.0.0",
        "react-dom": "^16.0.0"
    },
    "devDependencies": {
        "babel-core": "^6.21.0",
        "babel-loader": "^7.1.4",
        "babel-preset-env": "^1.6.1",
        "babel-preset-react": "^6.16.0",
        "babel-preset-stage-0": "^6.24.1",
        "path": "^0.12.7",
        "prop-types": "^15.6.0",
        "react": "^16.0.0",
        "react-dom": "^16.0.0",
        "webpack": "^4.5.0",
        "webpack-cli": "^3.2.1",
        "css-loader": "^2.1.0",
        "style-loader": "^0.23.1",
        "@trendmicro/react-sidenav": "^0.4.5"
    }
}

webpack.config.js:
var path = require('path');
 
module.exports = {
    mode: 'production',
    entry: './src/HermeSidebar.js',
    output: {
        path: path.resolve('lib'),
        filename: 'HermeSidebar.js',
        libraryTarget: 'commonjs2'
    },
    module: {
        rules: [
            {
                test: /\.js?$/,
                exclude: /(node_modules)/,
                use: 'babel-loader'
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader'],
            }
        ]
    }
}

.babelrc:
{
    "presets": [
        "react",
        "env",
        "stage-0"
    ]
}

.npmignore:
src
demo
.babelrc
webpack.config.js

scr:
HermeSidebar.js
ClickOutside.js
index.css

**Comment by roth1002** [comment]
Our props not provide and drilling the prop 「ref」 to our source

Please try other usage :)
