### ISSUE TITLE
Using Styled SideNav

### ISSUE THREAD

**Issue by Rohit-7** [trendmicro-frontend/react-sidenav#2]
Please tell me how I can import and use styled components from the npm package. It's very confusing and I'm fairly new to React. Loved your package by the way.

**Comment by cheton** [comment]
You can check out an example here:
https://github.com/trendmicro-frontend/react-sidenav/blob/master/examples/Styled/StyledSideNav.jsx

and use styled-component like below:

```jsx
import '@trendmicro/react-sidenav/dist/react-sidenav.css';
import SideNav, {
    Toggle,
    Nav,
    NavItem,
    NavIcon,
    NavText
} from '@trendmicro/react-sidenav';
import styled from 'styled-components';

// Styled SideNav
const StyledSideNav = styled(SideNav)`
`;
StyledSideNav.defaultProps = SideNav.defaultProps;

// Styled Nav
const StyledNav = styled(Nav)`
`;
StyledNav.defaultProps = Nav.defaultProps;

export {
    Toggle,
    StyledNav as Nav, // Styled Nav
    NavItem,
    NavIcon,
    NavText
};
export default StyledSideNav; // Styled SideNav
```

**Comment by Rohit-7** [comment]
Adding Icons to SubNav Items results in line split (the icon takes one whole line...). I've tried <span></span> and displaying inline-block. No use. How do I fix it??

**Comment by Rohit-7** [comment]
I'd like to add an avatar image to the NavInfoPane.....but the image isn't being displayed. Instead, it shows an icon of the image. Why can't I add the image? I have set the required height of the div but unable to display image. Please help.

**Comment by cheton** [comment]
You can paste your sample code here or demo your code at https://codesandbox.io/.

**Comment by Rohit-7** [comment]
Sorry, my bad. The location was wrong. How can I style only the hover menu that shows when the navbar isn't expanded. Because every time I try to style the &&&.hover part, other hover properties also change.

**Comment by cheton** [comment]
You can use CSS :not(selector) to match navitems only when the sidenav is not expanded:
```jsx
const StyledNav = styled(Nav)`
    &&:not([class*="sidenav---expanded"] {
        > [class*="sidenav---sidenav-navitem--"]:hover {
            // Hovered style
        }
    }
`;
```

**Comment by Rohit-7** [comment]
Thank you for quick replies. Your package saved the day for me. Could you please explain the syntax inside [class*="this part"]. If it's too much work, at least point me to a reference or documentation. Would be very helpful. Thanks again.

**Comment by cah-nikonesysouchanh** [comment]
I'm having issues with main content not pushing out like the demo? The main section is hidden under the sidenav. Any help would be appreciated!
