### ISSUE TITLE
Can't resolve 'styled-components' error after fresh install

### ISSUE THREAD

**Issue by alicerocheman** [trendmicro-frontend/react-sidenav#21]
`
Failed to compile.

./node_modules/react-sidenav/SideNav.js
Module not found: Can't resolve 'styled-components' in '[...]\node_modules\react-sidenav'
 `

occurs after installing version 3.1.7 with a fresh npm install (removed all node_modules to start over)
(resolved by installing styled-components manually)

**Comment by roth1002** [comment]
I thought you install styled-component in global

try to removed it since this repo use version 2.3.3 on devDependencies only
