### ISSUE TITLE
NavIcon not showing

### ISSUE THREAD

**Issue by deshario** [trendmicro-frontend/react-sidenav#24]
![image](https://user-images.githubusercontent.com/11426727/58556933-58771980-8247-11e9-8369-6491b8157387.png)

![image](https://user-images.githubusercontent.com/11426727/58557011-878d8b00-8247-11e9-8cec-fd11f835468a.png)

Icon not showing ... Is there anything missing from me

**Comment by aakhan89** [comment]
facing same issue, here is the demo of CodeSandbox

https://codesandbox.io/s/interesting-wave-c21jf

**Comment by aakhan89** [comment]
@deshario 
https://codesandbox.io/s/interesting-wave-c21jf

You can include Font Awesome css file in your html file, please see above mentioned link for your ready reference

**Comment by ghost** [comment]
thx @aakhan89  i was looking for a solution for hours ...
