### ISSUE TITLE
NavIcon not showing/working (URGENT)

### ISSUE THREAD

**Issue by aakhan89** [trendmicro-frontend/react-sidenav#25]
facing issue, here is the demo of CodeSandbox

https://codesandbox.io/s/interesting-wave-c21jf

**Comment by aakhan89** [comment]
**URGENT**

**Comment by aakhan89** [comment]
**ver : "react-sidenav": "^3.1.7",**

**Comment by cheton** [comment]
You didn’t include Font Awesome css file in your html file.

**Comment by aakhan89** [comment]
@cheton 
Thank you for you reply, working fine now,

why we can not use via installed package because I have already installed FontAwesoem package in my application 

And also you are requested to please mentioned about include Font Awesome css file in the html in your document or in Example

**Comment by aakhan89** [comment]
You may consider below too
**`https://styled-icons.js.org/`**

**Comment by rodrigorodrigues** [comment]
Hi @aakhan89,

I am very newbie on frontend it seems having the same issue the menu doesn't show after deployment using Docker but works fine testing locally, would you know how to solve that please? I have the font awesome css in both sides.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/398965/200111782-4a33432e-7139-457b-9283-5dc2f7de6b82.png">

<img width="353" alt="image" src="https://user-images.githubusercontent.com/398965/200111804-edd398fd-6846-487d-9c69-14618ab2e4e0.png">
