### ISSUE TITLE
Failed prop type: The prop `history` is marked as required in `Router`, but its value is `undefined`.

### ISSUE THREAD

**Issue by tienhd** [trendmicro-frontend/react-sidenav#30]
> {
  "name": "tictactoe",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@trendmicro/react-breadcrumbs": "^0.5.5",
    "@trendmicro/react-sidenav": "^0.4.5",
    "bootstrap": "4.3.1",
    "react": "^16.8.6",
    "react-bootstrap": "1.0.0-beta.8",
    "react-dom": "^16.8.6",
    "react-router-dom": "4.3.1",
    "react-scripts": "2.1.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

I used react-sidenav with router v4. 
<img width="682" alt="Screen Shot 2019-07-10 at 10 30 50 PM" src="https://user-images.githubusercontent.com/4455665/61131568-24507300-a4ec-11e9-878a-36021b7d7a4f.png">

I have end up with additional prop for history

>      <div>
                <Router history={createBrowserHistory()} >
                    <Route render={({ location, history }) => (
                        <React.Fragment>
                            <SideNav
                                onSelect={(selected) => {
                                    const to = '/' + selected;
                                    if (location.pathname !== to) {
                                        history.push(to);
                                    }
                                }}
                            >
                                <SideNav.Toggle />
                                <SideNav.Nav defaultSelected="home">
                                    <NavItem eventKey="home">
                                        <NavIcon>
                                            <i className="fa fa-fw fa-home" style={{ fontSize: '1.75em' }} />
                                        </NavIcon>
                                        <NavText>
                                            Home
                                        </NavText>
                                    </NavItem>
                                    <NavItem eventKey="devices">
                                        <NavIcon>
                                            <i className="fa fa-fw fa-device" style={{ fontSize: '1.75em' }} />
                                        </NavIcon>
                                        <NavText>
                                            Devices
                                        </NavText>
                                    </NavItem>
                                </SideNav.Nav>
                            </SideNav>
                            <main>
                                <Route path="/" exact component={props => <div/>} />
                                <Route path="/editor" component={Editor} />
                            </main>
                        </React.Fragment>
                    )}
                    />
                </Router>
            </div>

import  createBrowserHistory from 'history/createBrowserHistory';

**Comment by cheton** [comment]
This is not an issue related to this repo. Your code should look something like this:

```jsx
import { Router } from 'react-router';
import { createBrowserHistory } from 'history';

const history = createBrowserHistory()

<Router history={history}>
  <App/>
</Router>
```

See https://github.com/ReactTraining/history/releases/tag/v4.8.0-beta.0 for the change in react router v4.8.
