### ISSUE TITLE
Nav Icon doesn't show up

### ISSUE THREAD

**Issue by kixtaxwax** [trendmicro-frontend/react-sidenav#33]
I already imported css file, and it's working properly only except for Nav Icon showing.

**Comment by AntoLepejian** [comment]
Add this line to the header of your index.html and possibly install [react-fontawesome](https://www.npmjs.com/package/react-fontawesome)

`<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

**Comment by aakhan89** [comment]
@Twan2da 
You didn’t include Font Awesome css file in your html file.
