### ISSUE TITLE
 Unexpected use of 'history'

### ISSUE THREAD

**Issue by aakhan89** [trendmicro-frontend/react-sidenav#38]
` Unexpected use of 'history'  no-restricted-globals`

 onSelect={(selected) => {
                    const to = '/' + selected;
                    if (window.location.pathname !== to) {
                        history.push(to);
                    }
                }}

**Comment by aakhan89** [comment]
TypeError: Cannot read property 'location' of undefined

**Comment by roth1002** [comment]
Sincerely to use React Router v4 with React v16

Its on our readme
