### ISSUE TITLE
The onToggle callback does not work with react hooks setState.

### ISSUE THREAD

**Issue by jffin** [trendmicro-frontend/react-sidenav#48]
When I try to use SideNav setToggled callback with React hooks it fails with error "setState is not a function. 

```
function SideNavMenu() {
  const {toggled, setToggled} = useState(false);

  const sideNavClasses = () => {
    return `${toggled ? 'toggled' : ''}`
  };

  return (
    <StyledSideNav
      className={sideNavClasses()}
      onToggle={expanded => setToggled(expanded)}
    >
      <StyledToggle/>
      <Nav defaultSelected={'home'}>
           ...
      </Nav>
    </StyledSideNav>
  );
}

export default SideNavMenu;
```

Why does it happen?

**Comment by supertrens** [comment]
useState return an array not an object so you should have `  const [toggled, setToggled] = useState(false);
` instead of   `const {toggled, setToggled} = useState(false);`

**Comment by jffin** [comment]
Very stupid mistake (
Thanks a lot

**Comment by supertrens** [comment]
No worries mate, this happens to all of us... Happy learning
