### ISSUE TITLE
Nav height

### ISSUE THREAD

**Issue by arherzf8er** [trendmicro-frontend/react-sidenav#5]
Smooth implementation! But what if the main content will be `scrollable`?
Or if SideNav and top menu should be `sticky` to top?

Could you share a suitable snippet for this case or describe how you would do that?

![](https://i.imgur.com/pv77YVK.gif)

**Comment by cheton** [comment]
For simplicity, you can specify overflow-y property for your main content, or fix the position of side navigation bar.

**Comment by jfajardo** [comment]
Works for me

```
.nav-style {
    position: fixed;
    background: #e44745;
}

<SideNav className='nav-style' />
```
