### ISSUE TITLE
making navbar push content to the right?

### ISSUE THREAD

**Issue by pedrohba1** [trendmicro-frontend/react-sidenav#63]
I just copied the menu and set it up on my project. I want to make a way to push the content that is aside to the menu to the right and push it back to the left when the menu is collapsed. Is there an already implemented workaround for this?

As you can see the h1 saying dashboard is under the nav. I don't want it to be under the menu in any circunstance.
![issuepic1](https://user-images.githubusercontent.com/39497156/83437942-fd0dd780-a416-11ea-884b-52f5311bf865.png)
![issuepic2](https://user-images.githubusercontent.com/39497156/83437951-fed79b00-a416-11ea-82e4-b9b68f23723c.png)

**Comment by pedrohba1** [comment]
I saw that there is a o solution for this in the exampels, nevermind.

**Comment by Anoirwork** [comment]
Can i know how you did it please i'm tearing my hair to do it :'(
