### ISSUE TITLE
Change default min-width of SideNav

### ISSUE THREAD

**Issue by crismarucci** [trendmicro-frontend/react-sidenav#65]
Is there a way to change the 240px default width of the sidenav?
I found that in file sidenav-expanded.styl you can find that value, but I don't want to change it directly on the src file. Is there a way to configure it?

**Comment by crismarucci** [comment]
I have been fighting with this issue for two days. Ten minutes after posting the issue, I realized the answer... for tracking purpose, I post the answer:

const navWidthCollapsed = 64;
const navWidthExpanded = 280;

<SideNav style={{minWidth: expanded ? navWidthExpanded : navWidthCollapsed }} 

Tks.

**Comment by sunilsp77** [comment]
@crismarucci  How do you get "expanded" inside SideNav? Are you maintaining a local state? 
`<SideNav style={{minWidth: expanded ? navWidthExpanded : navWidthCollapsed }}`

**Comment by crismarucci** [comment]
Sorry for the delay in my answer! Yes, I'm maintaining a local state with that variable.

`
const navWidthCollapsed = 64;
const navWidthExpanded = 220;

class App extends React.Component {
  state = {
      selected: 'home',
      expanded: true
  };

  onSelect = (selected) => {
    this.setState({ selected: selected });
  };

  onToggle = (expanded) => {
      this.setState({ expanded: expanded });
  };
  
  render(){
    const { expanded } = this.state
    
    return (
      <Container>
          
        <Route render={({location, history}) => ( 
              <SideNav onToggle={this.onToggle} expanded={expanded}
                style={{...SideNavStyles, minWidth: expanded ? navWidthExpanded : navWidthCollapsed }}
                onSelect={(selected) => {
                  const to = '/' + selected;
                  if (location.pathname !== to) {
                    history.push(to);
                  }
                }}>
`

**Comment by sunilsp77** [comment]
> Sorry for the delay in my answer! Yes, I'm maintaining a local state with that variable.
> 
> `
> const navWidthCollapsed = 64;
> const navWidthExpanded = 220;
> 
> class App extends React.Component {
> state = {
> selected: 'home',
> expanded: true
> };
> 
> onSelect = (selected) => {
> this.setState({ selected: selected });
> };
> 
> onToggle = (expanded) => {
> this.setState({ expanded: expanded });
> };
> 
> render(){
> const { expanded } = this.state
> 
> ```
> return (
>   <Container>
>       
>     <Route render={({location, history}) => ( 
>           <SideNav onToggle={this.onToggle} expanded={expanded}
>             style={{...SideNavStyles, minWidth: expanded ? navWidthExpanded : navWidthCollapsed }}
>             onSelect={(selected) => {
>               const to = '/' + selected;
>               if (location.pathname !== to) {
>                 history.push(to);
>               }
>             }}>
> ```
> 
> `

Thanks for your answer.
