### ISSUE TITLE
How can I change the styling of the sidenav like max-width on expansion and min-width on collapsed?

### ISSUE THREAD

**Issue by sunilsp77** [trendmicro-frontend/react-sidenav#66]

**Comment by christrt9** [comment]
@sunilsp77  do you find the solution?

**Comment by sunilsp77** [comment]
> @sunilsp77 do you find the solution?

yes

`const navWidthCollapsed = 64;
const navWidthExpanded = 160;

<SideNav
            onSelect={(selected) => {
              const to = selected;
              if (props.location.pathname !== to) {
                props.history.push(to);
              }
            }}
            onToggle={onToggle}
            style={{
              backgroundColor: "#544b4b",
              position: "fixed",
              minWidth: expanded ? navWidthExpanded : navWidthCollapsed,
            }}
          >`
