### ISSUE TITLE
Icons do not appear

### ISSUE THREAD

**Issue by ghost** [trendmicro-frontend/react-sidenav#69]
I follow the whole procedure.
I installed all the packages and did all the imports but the icons still don't appear.
![screen](https://user-images.githubusercontent.com/57504641/87150641-c4350e00-c2b2-11ea-96ac-9d391c830e8d.PNG)
![Sidebar](https://user-images.githubusercontent.com/57504641/87150655-ca2aef00-c2b2-11ea-9a7e-63f7fadd6e34.PNG)

**Comment by orchardpark** [comment]
Hi MNzGenaud,

Installing font-awesome `npm install --save font-awesome` and adding the import `import 'font-awesome/css/font-awesome.min.css';` should make it work.

**Comment by MNzGenaud** [comment]
> Hi MNzGenaud,
> 
> Installing font-awesome `npm install --save font-awesome` and adding the import `import 'font-awesome/css/font-awesome.min.css';` should make it work.

**Comment by ghost** [comment]
Hi orchardpark,

Thanks i was able to fix it :)
