### ISSUE TITLE
import '@trendmicro/react-sidenav/dist/react-sidenav.css';

### ISSUE THREAD

**Issue by oneenam** [trendmicro-frontend/react-sidenav#7]
Could you please guide me why this error occurs when I am importing react-sidenav.css as you mentioned to import.

ERROR in ./node_modules/@trendmicro/react-sidenav/dist/react-sidenav.css 2:0
Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
| /*! react-sidenav v0.4.5 | (c) 2018 Trend Micro Inc. | MIT | https://github.com/trendmicro-frontend/react-sidenav */
> .sidenav---sidenav---_2tBP {
|   position: absolute;
|   top: 0;

**Comment by cheton** [comment]
You need to specify a CSS loader in your webpack config file.

See https://github.com/trendmicro-frontend/react-sidenav/blob/master/examples/webpack.config.js#L42
