### ISSUE TITLE
Removed from NPM?

### ISSUE THREAD

**Issue by dz1dz1on** [trendmicro-frontend/react-sidenav#72]
npm install --save react @trendmicro/react-sidenav
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@trendmicro%2freact-sidenav - Not found

Did you remove your library from npm?

**Comment by geeky-T** [comment]
The issue was from NPM cache repository, not of this library.

**Comment by dz1dz1on** [comment]
You are right. I am closing this issue.
