### ISSUE TITLE
NavIcon and position of the body linked to the sidenav.

### ISSUE THREAD

**Issue by ivanvorona** [trendmicro-frontend/react-sidenav#9]
Hi @cheton,
there are 2 more things i am struggling with:
1. Position of the body depending on the sidenav position, i can lock it fixed based on 
body {   margin-left: 60px; } but how do i link it to the SideNav itself? 
2. NavIcon - didn't find in your repository any link to the icon images. tried to use the styles on NavIcon 
list-style-image but it didn't work, could you please point me to the location where you control icon images?
still the same url: http://165.227.44.17:3000 and the same git repository as in previous question.
 Could you please direct me,
 Thank you in advance!

**Comment by ivanvorona** [comment]
I am all set with N2 NavIcon. still struggling with N1. if you could help - it would be much appreciated.

**Comment by cheton** [comment]
You can check the expanded state and change the margins accordingly:
https://github.com/trendmicro-frontend/react-sidenav/blob/master/examples/Default/index.jsx#L67

**Comment by Hienphamthe** [comment]
Hi @ivanvorona could you share the solution how to deal with NavIcon? Thanks a lot.

**Comment by Hienphamthe** [comment]
Nvm, found solution at #4
